//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMVisitasMedicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Visita = new HashSet<Visita>();
        }
    
        public int usu_id { get; set; }
        public string usu_nombre { get; set; }
        public string usu_apellidoPaterno { get; set; }
        public string usu_apellidoMaterno { get; set; }
        public Nullable<int> usu_edad { get; set; }
        public string usu_telefono { get; set; }
        public Nullable<int> sex_id { get; set; }
        public Nullable<int> est_id { get; set; }
        public Nullable<System.DateTime> usu_fecha_alta { get; set; }
        public Nullable<System.DateTime> usu_fecha_baja { get; set; }
        public Nullable<bool> usu_admin { get; set; }
        public string password { get; set; }
        public Nullable<bool> usu_permisoAltas { get; set; }
        public string nickname { get; set; }
    
        public virtual Estado_Usuario Estado_Usuario { get; set; }
        public virtual Sexo Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visita { get; set; }
    }
}
