//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMVisitasMedicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int vis_id { get; set; }
        public Nullable<System.DateTime> vis_fecha_cita { get; set; }
        public Nullable<int> usu_id { get; set; }
        public Nullable<int> med_id { get; set; }
        public Nullable<int> hos_id { get; set; }
        public Nullable<int> con_id { get; set; }
        public string vis_estado { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
